apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleJob
metadata:
  generateName: prehook-ansible
  namespace: aap
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  job_template_name: snow-create-change-record
  tower_auth_secret: aapaccess
